
name: Deployment

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'latest'

jobs:

  deploy-to-koyeb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          echo "PATH=$HOME/.koyeb/bin:$PATH" >> $GITHUB_ENV
      - name: Add configuration to Koyeb config file
        run: |
          cat << EOF >> $HOME/.koyeb.yaml
          api_url: https://api.koyeb.com
          token: ${{ secrets.KOYEB_TOKEN }}
          organization: ""
          debug: false
          EOF
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/my-react-app:${{ github.event.inputs.tag }}
      - name: Deploy to Koyeb
        run: koyeb app deploy ${{ secrets.KOYEB_APP_NAME }} --docker ${{ secrets.DOCKER_USERNAME }}/my-react-app:${{ github.event.inputs.tag }}
      - name: Get deployment status
        run: koyeb app get ${{ secrets.KOYEB_APP_NAME }} --output json | jq '.services[0].routes[0].uri'
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
